### ISSUE TITLE
CONTRIBUTORS File

### ISSUE THREAD

**Issue by drkennetz** [drkennetz/go-slack-chat-gpt3#11]
Need to outline contributors file

**Comment by hemantsoni42** [comment]
@drkennetz can you assign this to me ? 
Do I have to create new Contributors file?

**Comment by drkennetz** [comment]
@hemantsoni42 sure, it's assigned to you. Thanks again. I do not mind if it's new or reused, I'll just want to agree with it so I'll read it over.

**Comment by hemantsoni42** [comment]
Do you need a contributor file(typically contains a list of all the individuals who have contributed to the project in any way) or contribution file(procedure how to contribute in your repo issues) ?? 
Because both files contents are different.

**Comment by hemantsoni42** [comment]
This is **Contributing file** containing all the guidelines. If this is not the one you wanted please let me now I will create **Contributors file** also

**Comment by drkennetz** [comment]
Oh yeah, a contributors file would be great as well. I might be able to use CI to update the contributors file if I merge a Pr, but for now, could you also add into the "Contributing" file something like:

"Before opening a Pr for your changes, add your name to the Contributors.md file to get recognition for your contribution. I appreciate your help in this project!"

Also, I do not need to be added to the Contributors file.
