### ISSUE TITLE
CODE OF CONDUCT

### ISSUE THREAD

**Issue by drkennetz** [drkennetz/go-slack-chat-gpt3#13]
Need a code of conduct for the repo!

**Comment by hemantsoni42** [comment]
@drkennetz I want to work on this.
Please let me know your terms and conditions.

**Comment by drkennetz** [comment]
Let me get back to you on this. I'll have to think about it.

**Comment by drkennetz** [comment]
I looked at a few and I like this one best:

https://github.com/probot/template/blob/master/CODE_OF_CONDUCT.md

**Comment by hemantsoni42** [comment]
@drkennetz ok I will fill a Pull request for this also.
Can you please assign this to me.
