### ISSUE TITLE
Issue Template for repo

### ISSUE THREAD

**Issue by drkennetz** [drkennetz/go-slack-chat-gpt3#14]
Setup a template for opening issues in the repository

**Comment by hemantsoni42** [comment]
@drkennetz can you elaborate some more contents or I can fill a DEMO pull request for this.

**Comment by drkennetz** [comment]
@hemantsoni42 You can definitely do it, I'd like to have 3 basic issue templates that I'd like:

- bug_report.yml
- feature_request.yml
- documentation_update.yml

these would go inside of the .github directory in the repo, and you'd create an ISSUE_TEMPLATE directory in there where these 3 files would live. 

If you want to start with one, or you need some help I'd be happy to work through it with you. If you are already familiar with this process, then feel free to demo one and I'd be happy to give feedback in a PR.

**Comment by hemantsoni42** [comment]
Ok first I will try myself if I have any doubt or problem I will ask your help.
Thank you

**Comment by hemantsoni42** [comment]
Is this file looks good for your project or you want some changes in the file.
This is a demo file I will file another pull request for all three files first I want your approval on the file.

Apart from this we can also create a **PULL_REQUEST_TEMPLATE** this will help contributors during pull requests.

**Comment by hemantsoni42** [comment]
@drkennetz do you want a **Pull request Template** also???

**Comment by drkennetz** [comment]
@hemantsoni42 check it out - it looks awesome!

@hemantsoni42 Yeah I'd like a PR template, but let me open an issue for it. I'll close this and tag you. Thanks for your help.
