### ISSUE TITLE
[REQUEST] PR Template

### ISSUE THREAD

**Issue by drkennetz** [drkennetz/go-slack-chat-gpt3#17]
### Summary

We'd like a template for pull requests to this repository.

### Basic Example

Should address and issue #, have a summary describing what happens, and maybe basic usage? I'm open to interpretations here.

### Drawbacks

People have to work a bit harder to submit a PR, but I like the structure.

### Unresolved questions

@hemantsoni42 will you work on this?

**Comment by hemantsoni42** [comment]
yeah sure 
Thank you @drkennetz  for tagging me
