### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by drkennetz** [drkennetz/go-slack-chat-gpt3#3]
Currently, test coverage is sitting at 75%. I'd like to increase it, but would like to dedicate the time to other things right now. 

Missing coverage:

lines 19-20 in get_resonse.go (needs renamed)

lines 50-52 in event_handler.go

lines 36-39, 42-45, 53-58 in middleware.go (EASY WIN to setup missing cases)

**Comment by hemantsoni42** [comment]
@drkennetz this issue is open from more than 3 days I have no knowledge on Go language.
Is this issue can you solve by me or not ?

**Comment by drkennetz** [comment]
@hemantsoni42 I will solve this one - it won't be very hard for me I just haven't gotten around to it yet. It'll require me to refactor my tests a bit and I haven't had the time.

**Comment by drkennetz** [comment]
config coverage done, working on middleware
